name: Build and Deploy on AWS
on: 
  push: 
    branches:
      - main
jobs: 
  build:
    runs-on: self-hosted
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new backend envfile
        uses: SpicyPizza/create-envfile@v1.3
        with: 
          envkey_PORT: ${{secrets.PORT}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          envkey_POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          directory: back-end
          file_name: .env
          fail_on_empty: true
      - name: Make a new frontend envfile
        uses: SpicyPizza/create-envfile@v1.3
        with: 
          env_key_PORT: ${{secrets.VITE_APP_BACKEND_URL}}
          directory: front-end
          file_name: .env
          fail_on_empty: true
      - name: Run docker compose down
        run: docker compose down
      - name: Delete react docker volume
        run: if docker volume ls --quiet --filter name=password-generator-fullstack_react-volume | grep -q .; then docker volume rm passwordgenerator_react-volume; fi
      - name: Build docker images
        run: docker compose build
      - name: Run docker compose up
        run: docker compose up
