name: Pull Request on Github
on: [pull_request]
jobs: 
  PullRequest-Github:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1.3
        with: 
          env_key_PORT: ${{secrets.PORT}}
          env_key_DATABASE_URL: ${{secrets.DATABASE_URL}}
          env_key_POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
          env_key_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          env_key_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          directory: back-end
          file_name: .env.test
          fail_on_empty: true
      - name: Run tests backend
        run: docker compose -f docker-compose-test.yml run node npm run test
